---
# Elasticsearch Ansible Playbook
- hosts: all
  user: $user
  sudo: yes

  vars_files:
    - defaults/main.yml
    - vars/vagrant.yml

  tasks:
    - include: tasks/main.yml
    # - include: tasks/spm.yml spm_client_token=<enter your token>
