---

- include: java.yml
  when: elasticsearch_install_java
  tags:
    - elasticsearch
    - java

- include: timezone.yml
  when: elasticsearch_set_timezone
  tags:
    - elasticsearch
    - timezone

- include: install.yml
  tags:
    - elaticsearch
    - install

- include: configure.yml
  tags:
    - elaticsearch
    - config
  
- include: plugins.yml
  tags:
    - elasticsearch
    - plugins
