---
# Elasticsearch basic installation and configuration
- include: install.yml
  when: (elasticsearch_plugin_aws_version is defined)
  tags:
    - elasticsearch

# Install AWS Plugin
- include: aws.yml
  when: (elasticsearch_plugin_aws_version is defined)
  tags:
    - elasticsearch
    - aws

# Install Other Generic Plugins
- include: plugins.yml
  when: (elasticsearch_plugins is defined)
  tags:
    - elasticsearch

# Install custom JARs
- include: custom-jars.yml
  when: (elasticsearch_custom_jars is defined)
  tags:
    - elasticsearch

# Install Marvel Plugin
- include: marvel.yml
  when: (elasticsearch_plugin_marvel_version is defined)
  tags:
    - elasticsearch
    - marvel

# Restart Elasticsearch
- name: Restarting Elasticsearch
  service: name=elasticsearch state={{elasticsearch_state}} enabled={{ elasticsearch_enable }}
  tags:
    - elasticsearch

# Logstash
- include: logstash.yml
  tags:
    - logstash
    - elasticsearch
