---

# - name: plugins | Removing plugins
#   command: bin/elasticsearch-plugin remove "{{ item }}"
#   args:
#     chdir: "{{ elasticsearch_home_dir }}"
#   when: "{{ (elasticsearch_remove_plugins is defined) and (elasticsearch_remove_plugins | length) }}"
#   with_items: "{{ elasticsearch_remove_plugins }}"
  
- name: plugins | Installing plugins
  shell: bin/elasticsearch-plugin install --batch "{{ item }}"
  args:
    chdir: "{{ elasticsearch_home_dir }}"
  with_items: "{{ elasticsearch_plugins }}"
  register: es_plugins_installed
  changed_when: "'Installed' in es_plugins_installed.stdout"
  failed_when: "es_plugins_installed.rc != 0 and es_plugins_installed.stdout.find('already exists. To update the plugin') == -1"
