---

- name: Schedule daily task to clean Elasticsearch index
  cron:
    user:   root
    name:   daily-elasticsearch-index-clean
    # Runs daily at 7am UTC
    minute: 00
    hour:   05
    job:    /usr/local/bin/curator_cli delete_indices --filter_list '[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":{{ curator_index_limit }}}]' >> {{ elasticsearch_log_dir }}/elasticsearch-cron.log 2>&1
